GET http://localhost:3001/projects HTTP/1.1

###
GET http://localhost:3001/project/session HTTP/1.1

###
GET http://localhost:3001/project/file HTTP/1.1

###
GET http://localhost:3001/project/new HTTP/1.1

###
POST http://localhost:3001/project/new
Content-Type: application/json

{
"projectName": "project3",
"storedLocation": "/home/kali"
}

###
POST http://localhost:3001/project/session
Content-Type: application/json

{
"eventName": "Inspeccion",
"eventDate": "10/06/2022",
"analystInitials": "GO",
"canConnectorID": "123",
"vehicleID": "12345",
"baudRate": "5000",
"dbcFileName": "honda.dbc",
"blacklistFileName": "bl01.dbc",
"session": "63886c7f365d84655f52c8ff"
}

###
DELETE http://localhost:3001/project/delete-file

###
DELETE http://localhost:3001/project/delete-project/634c731b938045b0bf01b3f0
###
DELETE http://localhost:3001/project/delete-session/634bd2b3859dae316bcf05d0